---
apiVersion: v1
kind: Namespace
metadata:
  name: tcphello
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tcphello
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/eyablonowitz/tcphello
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tcphello
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: tcphello
  targetNamespace: tcphello